---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: vagrant-ubuntu
    groups:
    - all
    box: ubuntu/bionic64
    memory: 512
    cpus: 1
    provider_raw_config_args:
    - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        deploy_private_key: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACDAf9A+ZwzFWdnHSOma4qVg+oNQKHQQFYraXkxXW4utYQAAAJB9YcVWfWHF
          VgAAAAtzc2gtZWQyNTUxOQAAACDAf9A+ZwzFWdnHSOma4qVg+oNQKHQQFYraXkxXW4utYQ
          AAAEAbo03WpIhKJfyrxXS/CvQOzejODmHmjxfS/UUVImjPk8B/0D5nDMVZ2cdI6ZripWD6
          g1AodBAVitpeTFdbi61hAAAADW1nZWllckBiaWd4cHM=
          -----END OPENSSH PRIVATE KEY-----
        git_repo: "git@gitlab.licar.exp.dc.uba.ar:sherlockfog/sherlockfog.git"

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: 1
