---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal python-pip)
    become: true
    changed_when: false

  - name: install deps
    apt:
      pkg:
        - python3
        - python3-pip
        - python3-setuptools
        - python3-pexpect
        - python3-paramiko
        - python3-networkx
        - python3-matplotlib
        - python3-pytest
        - cgroup-tools
      state: latest
      update_cache: yes
    become: true
    changed_when: false

  - name: Install compat for python<3.7
    command: pip3 install importlib_resources
    become: yes
    changed_when: false

  - name: Install testinfra for pytest inside molecule
    command: pip3 install testinfra
    become: yes
    changed_when: false

  - name: Install licar deploy key
    copy:
      content: "{{ deploy_private_key }}"
      dest: /home/vagrant/.ssh/deploy_key
      mode: 0600

  - name: Clone SherlockFog
    git:
      repo: "{{ git_repo }}"
      dest: /home/vagrant/sherlockfog
      key_file: /home/vagrant/.ssh/deploy_key
      accept_hostkey: yes

  - name: Install SherlockFog
    raw: cd /home/vagrant/sherlockfog && python3 setup.py install
    become: yes

  - name: Generate root ssh key
    raw: yes y | ssh-keygen -q -N "" -f /root/.ssh/id_ecdsa -t ecdsa
    become: yes

  - name: Install root ssh key in authorized keys
    copy:
      src: /root/.ssh/id_ecdsa.pub
      dest: /root/.ssh/authorized_keys
      remote_src: yes
    become: yes

  - name: Disable strict host key checking for root
    raw: echo StrictHostKeyChecking no >> /root/.ssh/config
    become: yes
